envir = env.ENVIR_DIR

server.document-root = envir + "/www"
server.port = 8080

server.modules = (
    "mod_fastcgi",
    "mod_redirect"
)
server.max-keep-alive-requests = 8
server.max-keep-alive-idle = 3
server.max-read-idle = 10
server.max-write-idle = 10

index-file.names = ( "index.html" )

mimetype.assign = (
    ".html" => "text/html",
    ".js"   => "application/javascript",
    ".css"  => "text/css",
    ".mp4"  => "video/mp4",
    ".jpeg" => "image/jpeg",
    ".jpg"  => "image/jpeg"
)

fastcgi.server = (
    "/login" => ((
        "socket" => "/tmp/FastCGI.sock",
        "bin-path" => envir + "/bin/FastCGI",
        "max-procs" => 1,
        "check-local" => "disable",
        "bin-environment" => (
            "ENVIR_DIR" => env.ENVIR_DIR
        )
    )),
    "/preview" => ((
        "socket" => "/tmp/FastCGI.sock",
        "bin-path" => envir + "/bin/FastCGI",
        "max-procs" => 1,
        "check-local" => "disable",
        "bin-environment" => (
            "ENVIR_DIR" => env.ENVIR_DIR
        )
    )),
    "/api/v1" => ((
        "socket" => "/tmp/FastCGI.sock",
        "bin-path" => envir + "/bin/FastCGI",
        "max-procs" => 1,
        "check-local" => "disable",
        "bin-environment" => (
            "ENVIR_DIR" => env.ENVIR_DIR
        )
    ))
)

url.redirect = (
    "^/$" => "/preview"
)
