envir = env.ENVIR_DIR

server.document-root = envir + "/www"
server.port = 80

server.modules = (
    "mod_openssl",
    "mod_redirect",
    "mod_fastcgi",
    "mod_proxy",
    "mod_alias"
)
server.max-keep-alive-requests = 8
server.max-keep-alive-idle = 3
server.max-read-idle = 3600
server.max-write-idle = 3600
server.stream-request-body = 0

# HTTP(s) port
# Redirect "http" -> "https"
$HTTP["scheme"] == "http" {
    url.redirect = (
        "" => "https://${url.authority}${url.path}${qsa}"
    )
}

$SERVER["socket"] == ":443" {
    ssl.engine  = "enable"
    ssl.pemfile = envir + "/etc/server.crt"
    ssl.privkey = envir + "/etc/server.key"
}

proxy.header = (
    "upgrade" => "enable"
)

index-file.names = ( "index.html" )

mimetype.assign = (
    ".html" => "text/html",
    ".js"   => "application/javascript",
    ".wasm" => "application/wasm",
    ".css"  => "text/css",
    ".json" => "application/json",
    ".mp4"  => "video/mp4",
    ".flv"  => "video/x-flv",
    ".png"  => "image/png",
    ".jpeg" => "image/jpeg",
    ".jpg"  => "image/jpeg",
    ".svg"  => "image/svg+xml",
    ""      => "application/octet-stream"
)

fastcgi.server = (
    "/login" => ((
        "socket" => "/tmp/FastCGI.sock",
        "bin-path" => envir + "/bin/FastCGI",
        "max-procs" => 1,
        "check-local" => "disable",
        "bin-environment" => (
            "ENVIR_DIR" => envir
        )
    )),
    "/preview" => ((
        "socket" => "/tmp/FastCGI.sock",
        "bin-path" => envir + "/bin/FastCGI",
        "max-procs" => 1,
        "check-local" => "disable",
        "bin-environment" => (
            "ENVIR_DIR" => envir
        )
    )),
    "/api/v1" => ((
        "socket" => "/tmp/FastCGI.sock",
        "bin-path" => envir + "/bin/FastCGI",
        "max-procs" => 1,
        "check-local" => "disable",
        "bin-environment" => (
            "ENVIR_DIR" => envir
        )
    ))
)

$HTTP["url"] == "/ws/live0.flv" {
    proxy.server = (
        "" => ((
            "host" => "127.0.0.1",
            "port" => 9000
        ))
    )
}

$HTTP["url"] == "/ws/live1.flv" {
    proxy.server = (
        "" => ((
            "host" => "127.0.0.1",
            "port" => 9000
        ))
    )
}

alias.url += (
    "/records/" => "/mnt/sdcard/"
)
